Settings:
    path:    /
    defaults: { _controller: CmsWebSiteBundle:Settings:index }

Settings-newPage:
    path:    /new-page/step-2
    defaults: { _controller: CmsWebSiteBundle:Pages:newPage }

Settings-browsePages:
    path:    /browse-pages
    defaults: { _controller: CmsWebSiteBundle:Pages:browsePages }

Settings-editPage:
    path:    /edit-page/{pageName}
    defaults: { _controller: CmsWebSiteBundle:Pages:editPages }

Settings-changeTemplate:
    path:    /change-template/{pageName}
    defaults: { _controller: CmsWebSiteBundle:Pages:changeTemplate }

Settings-settingsPage:
    path:    /page-settings
    defaults: { _controller: CmsWebSiteBundle:Pages:pageSettings }

Settings-newMenu:
    path:    /Menu/new-menu
    defaults: { _controller: CmsWebSiteBundle:Menu:newMenu }

Settings-manageMenus:
    path:    /Menu/manage-menus
    defaults: { _controller: CmsWebSiteBundle:Menu:manageMenus }

Settings-editMenu:
    path:    /Menu/edit-menu
    defaults: { _controller: CmsWebSiteBundle:Menu:editMenu }

Settings-getMenuRender:
    path:    /Menu/getMenu/{id}
    defaults: { _controller: CmsWebSiteBundle:Menu:getMenuView }

Settings-selectMenuWysiwyg:
    path:    /Menu/select-menu-wysiwyg
    defaults: { _controller: CmsWebSiteBundle:Menu:selectMenuWysiwyg }



Settings-getLog:
    path:    /Debug/getLog
    defaults: { _controller: CmsWebSiteBundle:Debug:getLog }

Settings-clearLog:
    path:    /Debug/clearLog
    defaults: { _controller: CmsWebSiteBundle:Debug:clearLog }