ini-settings:
    pattern:  /
    defaults: { _controller: CmsWebSiteBundle:Initialisation:initialisationDb }

ini-settings-createDB:
    pattern:  /createDB
    defaults: { _controller: CmsWebSiteBundle:Initialisation:createDB }

ini-settings-admin:
    pattern:  /admin
    defaults: { _controller: CmsWebSiteBundle:Initialisation:initialisationAdmin }

ini-cache:
    pattern:  /cacheClear
    defaults: { _controller: CmsWebSiteBundle:Initialisation:cacheClear }

