Uploads-uploadImage-wysiwyg:
    path:    /Images-wysiwyg
    defaults: { _controller: CmsWebSiteBundle:Uploads:imagesWysiwyg }

Uploads-uploadImage:
    path:    /Images
    defaults: { _controller: CmsWebSiteBundle:Uploads:images }

Uploads-browseImage:
    path:    /browse-images
    defaults: { _controller: CmsWebSiteBundle:Uploads:browseImages }

Uploads-selectImage-wysiwyg:
    path:    /selectImage-wysiwyg
    defaults: { _controller: CmsWebSiteBundle:Uploads:selectImagesWysiwyg }
