Settings-GetTemplate:
    path:    /new-template/step-1
    defaults: { _controller: CmsWebSiteBundle:Templates:getTemplate }

Settings-initTemplate:
    path:    /new-template/step-2
    defaults: { _controller: CmsWebSiteBundle:Templates:initTemplate }

Settings-otherAssetsUpload:
    path:    /new-template/step-3
    defaults: { _controller: CmsWebSiteBundle:Templates:otherAssetsUpload }

Settings-selectTemplate:
    path:    /new-page/step-1
    defaults: { _controller: CmsWebSiteBundle:Templates:selectTemplate }

Settings-manageTemplates:
    path:    /manage-templates
    defaults: { _controller: CmsWebSiteBundle:Templates:manageTemplates }
