Index:
    path:    /
    defaults: { _controller: CmsWebSiteBundle:WebSite:index }
PageNoFound:
    path:    /page-no-found
    defaults: { _controller: CmsWebSiteBundle:WebSite:pageNoFound }
Page:
    path:    /{path}
    defaults: { _controller: CmsWebSiteBundle:WebSite:page }
