parameters:
#    cms_web_site.example.class: Cms\WebSiteBundle\Example

services:
#    cms_web_site.example:
#        class: %cms_web_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
