parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: cms
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host:  smtp.gmail.com
    mailer_user: youenn.pennarun
    mailer_password: null
    initialised : 'true'
    locale: en
    secret: 3c18a83c6680e779969317536cb8d893
    base-path: /cms
