security:
    encoders:
        Cms\WebSiteBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_USER:        ROLE_USER
        ROLE_AUTHOR:        [ROLE_USER,ROLE_AUTHOR]
        ROLE_ADMIN:       [ROLE_ADMIN,ROLE_AUTHOR]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        administrators:
            entity: { class: CmsWebSiteBundle:User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/Settings/login$
            security: false

        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                check_path: /Settings/login_check
                login_path: /Settings/login
            logout:
                path:   /Settings/logout
                target: /
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/Settings/User/manage-users, roles: IS_AUTHENTICATED_ANONYMOUSLY  }
        - { path: ^/Settings/new-page, roles: ROLE_AUTHOR  }
        - { path: ^/Settings/new-category, roles: ROLE_AUTHOR  }
        - { path: ^/Settings/Uploads, roles: ROLE_AUTHOR  }
        - { path: ^/Settings, roles: ROLE_ADMIN }
