<?php

namespace Proxies\__CG__\Cms\WebSiteBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Template extends \Cms\WebSiteBundle\Entity\Template implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function analyseFile()
    {
        $this->__load();
        return parent::analyseFile();
    }

    public function analyseCss($cssFilePath)
    {
        $this->__load();
        return parent::analyseCss($cssFilePath);
    }

    public function editCss($cssFilePath, $toBeReplaced)
    {
        $this->__load();
        return parent::editCss($cssFilePath, $toBeReplaced);
    }

    public function editFile($linesToBeReplaced, $imgToReplace)
    {
        $this->__load();
        return parent::editFile($linesToBeReplaced, $imgToReplace);
    }

    public function toDBPreparation($variable)
    {
        $this->__load();
        return parent::toDBPreparation($variable);
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setPath($path)
    {
        $this->__load();
        return parent::setPath($path);
    }

    public function getPath()
    {
        $this->__load();
        return parent::getPath();
    }

    public function setVariableArray($variableArray)
    {
        $this->__load();
        return parent::setVariableArray($variableArray);
    }

    public function getVariableArray()
    {
        $this->__load();
        return parent::getVariableArray();
    }

    public function setAssetsString($assetsString)
    {
        $this->__load();
        return parent::setAssetsString($assetsString);
    }

    public function getAssetsString()
    {
        $this->__load();
        return parent::getAssetsString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'path', 'variableArray', 'assetsString');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}